name: reinforcement_learning_assignment
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - plotly
  - seaborn
  - matplotlib
  - pytorch
  - cudatoolkit=11.7
  - gymnasium
  - imageio
  - pip
  - pip:
    - grid2op
    - lightsim2grid
    - stable-baselines3[extra]
#    - "stable_baselines3[extra,tests,docs] @ git+https://github.com/DLR-RM/stable-baselines3"